-- 문화/레저 카테고리 시드 (0007)
-- 작성: 2026-05-14
-- 원본: data/culture_leisure_cleaned.csv
-- 정책: brands ON CONFLICT (name) DO NOTHING — 중복 SKIP

INSERT INTO public.brands (name, category) VALUES
  ('CGV', '문화/레저'),
  ('메가박스', '문화/레저'),
  ('롯데시네마', '문화/레저'),
  ('영풍문고', '문화/레저'),
  ('알라딘', '문화/레저'),
  ('롯데월드', '문화/레저'),
  ('야놀자', '문화/레저'),
  ('여기어때', '문화/레저'),
  ('인터파크 티켓', '문화/레저'),
  ('에버랜드', '문화/레저')
ON CONFLICT (name) DO NOTHING;

INSERT INTO public.discounts (brand_id, provider, type, rate, limit_amount, conditions, is_stackable, source_url, updated_at) VALUES
  ((SELECT id FROM public.brands WHERE name = 'CGV'), 'CGV(CJ ONE 멤버십)', '포인트 적립', '상품/서비스 구매 시 결제 금액의 0.3%~5% CJ ONE 포인트 기본 적립. 1,000P 이상 시 전국 CGV 영화 관람·매점 이용 시 1P=1원 현금처럼 사용 가능. 매월 1일~말일 제휴 브랜드 3개 이상 이용 시 적립 포인트의 20% 추가 적립.', '1P=1원, 1,000P 이상 사용 가능', 'CJ ONE 회원 가입자 | 기간: 상시', NULL, 'https://section.cgv.co.kr/user/membership/', '2026-05-13T00:00:00+09:00'),
  ((SELECT id FROM public.brands WHERE name = 'CGV'), 'SKT T멤버십', '할인', '영화 관람권(11,000원 이상) 예매 시 최대 4,000원 할인. 11,000원권 1,000원 / 12,000원권 2,000원 / 13,000원권 3,000원 / 14,000원 이상 4,000원 할인. T 멤버십 앱에서 예매 시 적용.', '하루 1회, 1회 최대 5좌석, 2D 일반 영화에 한함', 'T 멤버십 전등급(VIP/GOLD/SILVER) | 기간: 상시', NULL, 'https://sktmembership.tworld.co.kr/mps/pc-bff/benefitbrand/detail.do?brandId=973', '2026-05-13T00:00:00+09:00'),
  ((SELECT id FROM public.brands WHERE name = 'CGV'), 'SKT T멤버십 VIP PICK', '할인/무료관람', '무료 관람 연 3회 + 평일/주말 관람 1+1 연 9회(2D 일반 영화) + 특별관(CGV 4DX 2D / SCREENX 2D / IMAX 2D) 할인 가격 예매 연 12회 추가. 무료/1+1은 예매 정가 7,000원 이상 영화에만 적용.', 'VIP PICK 통합 월 1회(연 12회). 특별관 예매 혜택은 별도 연 12회 추가 제공', 'T 멤버십 VIP 등급 | 기간: 상시', NULL, 'https://sktmembership.tworld.co.kr/mps/pc-bff/benefitbrand/detail.do?brandId=973', '2026-05-13T00:00:00+09:00'),
  ((SELECT id FROM public.brands WHERE name = 'CGV'), 'KT 멤버십', '할인', 'KT 멤버십 앱/웹 예매 시 12,000~16,000원 티켓 최대 5,000원 할인. 12,000원/1,000원, 13,000원/2,000원, 14,000원/3,000원, 15,000원/4,000원, 16,000원/5,000원 할인. 동반 4인까지 동일 할인 제공.', '일 1회. 2D(일반상영관/컴포트석/MYBOX)에 한함', 'KT 멤버십 전등급 | 기간: 상시', NULL, 'https://membership.kt.com/discount/partner/C23/65/PartnerDetail.do', '2026-05-13T00:00:00+09:00'),
  ((SELECT id FROM public.brands WHERE name = 'CGV'), 'KT 멤버십', '할인/현장', 'CGV 현장 매점 콤보 3,000원 할인. CGV콤보·더블콤보·라지콤보 대상(맛 변경·사이즈 변경 시 추가금액 발생). 쿠폰 다운로드 후 영화관 내 현장 키오스크에서 적용.', '월 1회. 매월 선착순 3만명 한정', 'KT 멤버십 전등급 | 기간: 상시', NULL, 'https://membership.kt.com/discount/partner/C23/65/PartnerDetail.do', '2026-05-13T00:00:00+09:00'),
  ((SELECT id FROM public.brands WHERE name = 'CGV'), 'LG U+ 멤버십', '할인/무료관람', 'VIP콕(영화 예매) 선택 시 무료 예매 연 3회 + 1+1 예매 연 9회. U+one 앱 또는 U+ 홈페이지에서 예매.', '연 12회(무료 3 + 1+1 9). VIP콕은 분기별 1회 변경 가능', 'LG U+ 멤버십 VIP/VVIP 등급 | 기간: 상시', NULL, 'https://www.lguplus.com/benefit-membership/movie-booking/guest', '2026-05-13T00:00:00+09:00'),
  ((SELECT id FROM public.brands WHERE name = '메가박스'), 'SKT T멤버십', '할인', '영화 관람권(11,000원 이상) 예매 시 최대 4,000원 할인. 11,000원권 1,000원 / 12,000원권 2,000원 / 13,000원권 3,000원 / 14,000원 이상 4,000원 할인. T 멤버십 앱에서 예매 시 적용.', '하루 1회, 1회 최대 5좌석, 2D 일반 영화에 한함', 'T 멤버십 전등급(VIP/GOLD/SILVER) | 기간: 상시', NULL, 'https://sktmembership.tworld.co.kr/mps/pc-bff/benefitbrand/detail.do?brandId=968', '2026-05-13T00:00:00+09:00'),
  ((SELECT id FROM public.brands WHERE name = '메가박스'), 'SKT T멤버십 VIP PICK', '할인/무료관람', '무료 관람 연 3회 + 평일/주말 관람 1+1 연 9회(2D 일반 영화) + 특별관 할인 가격 예매 연 12회 추가. 무료/1+1은 예매 정가 7,000원 이상 영화에만 적용.', 'VIP PICK 통합 월 1회(연 12회). 특별관 예매 혜택은 별도 연 12회 추가 제공', 'T 멤버십 VIP 등급 | 기간: 상시', NULL, 'https://sktmembership.tworld.co.kr/mps/pc-bff/benefitbrand/detail.do?brandId=968', '2026-05-13T00:00:00+09:00'),
  ((SELECT id FROM public.brands WHERE name = '메가박스'), 'KT 멤버십', '할인', 'KT 멤버십 앱/웹 예매 시 최대 6,000원 할인. 평일(월~목) 11,000~16,000원 티켓 1,000~6,000원 할인. 주말(금~일) 12,000~17,000원 티켓 1,000~6,000원 할인. 동반 4인까지 동일 할인 제공.', '일 1회(2D)', 'KT 멤버십 전등급 | 기간: 상시', NULL, 'https://membership.kt.com/discount/partner/C23/67/PartnerDetail.do', '2026-05-13T00:00:00+09:00'),
  ((SELECT id FROM public.brands WHERE name = '메가박스'), 'KT 멤버십', '할인/현장', '메가박스 현장 매점 콤보 2,000원 할인. 메가박스 러브콤보·더블콤보 대상(맛 변경·사이즈 변경 시 추가금액 발생). 쿠폰 다운로드 후 메가박스 앱(모바일 오더) 또는 무인발권기에서 적용.', '월 1회, 콤보 1개당 1개의 쿠폰만 적용', 'KT 멤버십 전등급 | 기간: 상시', NULL, 'https://membership.kt.com/discount/partner/C23/67/PartnerDetail.do', '2026-05-13T00:00:00+09:00'),
  ((SELECT id FROM public.brands WHERE name = '롯데시네마'), '롯데시네마(L.POINT)', '포인트 적립', '영화 관람 회원 등급에 따라 티켓 결제 금액의 L.POINT 적립. VIP플래티넘 10% / VIP골드 5% / VIP실버 5% / 일반회원 0.5%. 스위트샵(매점)은 결제 금액의 0.5% 적립. 관람 다음날 적립.', 'L.POINT 가입 후 적립, 일부 영화관 제외', 'L.POINT 가입 + 롯데시네마 회원 | 기간: 상시', NULL, 'https://www.lottecinema.co.kr/NLCMW/Mypage/MemberVipzone', '2026-05-13T00:00:00+09:00'),
  ((SELECT id FROM public.brands WHERE name = '롯데시네마'), 'KT 멤버십', '할인', 'KT 멤버십 앱/웹 예매 시 일반관 2D 영화 11,000원 이상 티켓에 한해 할인. 본인+동반 4인까지 동일 할인 제공.', '일 1회', 'KT 멤버십 전등급 | 기간: 상시', NULL, 'https://m.membership.kt.com/culture/movie/s_MovieInfo.do', '2026-05-13T00:00:00+09:00'),
  ((SELECT id FROM public.brands WHERE name = '롯데시네마'), 'KT 멤버십 VVIP/VIP 초이스', '무료예매', 'VVIP/VIP 초이스 영화관람권 무료예매. 무료예매 시 동반 4인까지 할인. VVIP/VIP 초이스 무료예매는 롯데시네마에서만 이용 가능.', '2026년 기준 VVIP 연 12회(프로모션), VIP 연 6회', 'KT 멤버십 VVIP/VIP 등급 | 기간: 상시(2026년 한정 프로모션 횟수 포함)', NULL, 'https://m.membership.kt.com/culture/movie/s_MovieInfo.do', '2026-05-13T00:00:00+09:00'),
  ((SELECT id FROM public.brands WHERE name = '영풍문고'), '영풍문고(북클럽 멤버십)', '포인트 적립', '인터넷에서 도서 구매 시 최대 5% 적립금 지급. 매장 도서 발송 완료 후 자동으로 적립금 적립.', '도서 구매 시 자동 적립', '북클럽 가입 회원 | 기간: 상시', NULL, 'http://www.ypbooks.co.kr/customer_center.yp?targetpage=helper_accumulation&pageflag=1', '2026-05-13T00:00:00+09:00'),
  ((SELECT id FROM public.brands WHERE name = '영풍문고'), '영풍문고(북클럽 멤버십)', '포인트 적립', '매장 구매 시 도서 2% / 문구 상품 1% 적립금 지급. 구매 직후 자동 적립(다음날 확인 가능).', '매장 구매 시 자동 적립', '북클럽 가입 회원 | 기간: 상시', NULL, 'http://www.ypbooks.co.kr/customer_center.yp?targetpage=helper_accumulation&pageflag=1', '2026-05-13T00:00:00+09:00'),
  ((SELECT id FROM public.brands WHERE name = '영풍문고'), '영풍문고(북클럽 골드·플래티넘)', '포인트 적립/추가', '기본 적립(도서 2~5%, 문구 1%) 외에 골드·플래티넘 회원은 최대 5% 마일리지 안에서 추가 혜택 부여. 골드: 직전 3개월 20만원 이상 구매. 플래티넘: 직전 3개월 30만원 이상 구매.', '기본 적립과 별도', '북클럽 골드(직전 3개월 20만원+) / 플래티넘(직전 3개월 30만원+) | 기간: 상시(등급 자격 기간 동안)', NULL, 'http://www.ypbooks.co.kr/customer_center.yp?targetpage=helper_accumulation&pageflag=1', '2026-05-13T00:00:00+09:00'),
  ((SELECT id FROM public.brands WHERE name = '영풍문고'), '영풍문고(북클럽 멤버십)', '포인트 사용', '회원 인증 받은 회원에 한해 적립금 1,000원 이상 누적 시 영풍문고 본·지점 및 인터넷에서 사용 가능.', '1,000원 이상 누적 시 사용', '북클럽 가입 + 회원 인증 회원 | 기간: 상시', NULL, 'http://www.ypbooks.co.kr/customer_center.yp?targetpage=helper_accumulation&pageflag=1', '2026-05-13T00:00:00+09:00'),
  ((SELECT id FROM public.brands WHERE name = '알라딘'), '알라딘(멤버십)', '적립금', '멤버십 등급별 몰별 적립금. 플래티넘: 2만↑1,000원 / 4만↑2,000원 / 6만↑2,500원 / 8만↑3,000원. 골드: 2만↑1,000원 / 4만↑2,000원 / 6만↑2,500원. 실버: 2만↑1,000원 / 4만↑2,000원.', '주문 총액 기준 단계별 적립금', '알라딘 멤버십 회원(실버/골드/플래티넘) | 기간: 상시(자격 기간 3개월)', NULL, 'https://www.aladin.co.kr/m/mcscenter.aspx?pType=faqview&faqid=68&categoryid=88', '2026-05-13T00:00:00+09:00'),
  ((SELECT id FROM public.brands WHERE name = '알라딘'), '알라딘(멤버십)', '마일리지 추가 적립', '등급에 따라 구매액의 3%~1% 차등 추가 마일리지 적립. 단, 해당 주문에 알라딘 직배송중고·외국도서·잡지·음반·DVD·알라딘굿즈·유료 사은품 중 1종 이상(도서정가제 비대상) 반드시 포함, 최대 ''국내도서 외 상품'' 구매 금액만큼.', '주문별 비대상 상품 포함 여부에 따라 적용', '알라딘 멤버십 회원 | 기간: 상시', NULL, 'https://blog.aladin.co.kr/cscenter/1451722', '2026-05-13T00:00:00+09:00'),
  ((SELECT id FROM public.brands WHERE name = '알라딘'), '알라딘(멤버십)', '적립금', '모바일에서 3만원 이상 구매 시 2,000원 몰별 적립금 추가 지급. 전 등급(실버/골드/플래티넘) 공통.', '주문 1건당 1회', '알라딘 멤버십 회원 | 기간: 상시', NULL, 'https://blog.aladin.co.kr/cscenter/1451720', '2026-05-13T00:00:00+09:00'),
  ((SELECT id FROM public.brands WHERE name = '알라딘'), '알라딘', '마일리지 추가', '5만원 이상 구매 시 추가 마일리지 2,000점 제공. 각 건별 주문 총액 기준(중고도서·외국도서·잡지·음반·DVD·기프트 등 포함 5만원 이상).', '1회 주문당 1회. 2회 이상 주문 합산 불가', '알라딘 회원 | 기간: 상시', NULL, 'https://www.aladin.co.kr/cs_center/wcs_guide_detail.aspx?pn=mybank_07', '2026-05-13T00:00:00+09:00'),
  ((SELECT id FROM public.brands WHERE name = '알라딘'), '알라딘', '마일리지 사용', '마일리지 10원 이상 누적 시 적립금으로 전환 가능(전환 후 취소 불가). 주문 시 결제에 현금처럼 사용 가능. 마일리지 유효기간 1년, 마일리지 전환 적립금 6개월.', '10원 이상 누적 시 전환', '알라딘 회원 | 기간: 상시', NULL, 'https://blog.aladin.co.kr/cscenter/1451722', '2026-05-13T00:00:00+09:00'),
  ((SELECT id FROM public.brands WHERE name = '롯데월드'), '롯데월드(L.POINT 결제)', '할인', 'L.POINT로 100% 결제 시 종합이용권 최대 47% 할인. 포인트 부족 시 즉시 충전 가능. 생애 첫 L.POINT 충전(30,000P 이상) 시 5,000P 적립.', '현장 유인매표소 결제 한정', 'L.POINT 회원 | 기간: 상시', NULL, 'https://adventure.lotteworld.com/kor/price/benefit/information/view.do?detailsKey=2419', '2026-05-13T00:00:00+09:00'),
  ((SELECT id FROM public.brands WHERE name = '롯데월드'), '삼성카드 롯데월드', '할인', '롯데월드 운영 시설 이용권 50% 현장 할인(본인 및 동반 1인까지). 매직패스 프리미엄 구매 혜택, 직영 기념품샵·부대시설 할인 등 추가 혜택 제공.', '본인 + 동반 1인', '삼성카드 롯데월드 카드 회원 | 기간: 상시(카드 보유 기간)', NULL, 'https://adventure.lotteworld.com/kor/price/lotteworldcard/contentsid/703/index.do', '2026-05-13T00:00:00+09:00'),
  ((SELECT id FROM public.brands WHERE name = '롯데월드'), 'SKT T멤버십 기본제휴', '할인', '본인 40% + 동반 3인 30%(VIP/Gold) 또는 20%(Silver) 현장 할인. 현장 유인매표소 또는 티켓 키오스크에서 SK텔레콤 T멤버십 회원 인증 후 적용.', 'SKT 멤버십 카드당 1일 1회', 'T 멤버십 전등급(VIP/Gold/Silver) + 본인 + 동반 3인 | 기간: 상시', NULL, 'https://adventure.lotteworld.com/kor/price/benefit/information/view.do?detailsKey=2629', '2026-05-13T00:00:00+09:00'),
  ((SELECT id FROM public.brands WHERE name = '롯데월드'), 'KT 멤버십', '할인', '본인 + 동반 3인까지 현장 할인. VIP 등급 35% 할인 / 기타 등급(VVIP·Gold·Silver·White·일반) 30% 할인. 현장 유인매표소에서 KT 멤버십 회원 인증 및 적용.', '본인 소유 멤버십 카드에 한하여 우대 적용', 'KT 멤버십 전등급 + 본인 + 동반 3인 | 기간: 상시', NULL, 'https://adventure.lotteworld.com/kor/price/benefit/information/view.do?detailsKey=1171', '2026-05-13T00:00:00+09:00'),
  ((SELECT id FROM public.brands WHERE name = '롯데월드'), 'LG U+ 멤버십(VIP콕)', '할인', 'VIP콕(영화 예매와 별도 콕 선택지) 선택 시 본인 + 동반 3인 현장 할인. 현장 유인매표소 또는 티켓 키오스크에서 LG U+ 멤버십 회원 인증 후 적용.', '월 1회 이용 가능', 'LG U+ 멤버십 VIP/VVIP 등급(VIP콕 선택) | 기간: 상시', NULL, 'https://adventure.lotteworld.com/kor/price/benefit/information/view.do?detailsKey=2650', '2026-05-13T00:00:00+09:00'),
  ((SELECT id FROM public.brands WHERE name = '야놀자'), '야놀자(NOL 포인트)', '포인트 적립', '야놀자 자체 프로모션 기준 NOL 포인트 적립. 결제 시 보유 NOL 포인트로 결제 금액 전액 또는 일부 사용 가능. 전액 결제 시 별도 본인 확인(ARS) 절차.', '프로모션별 적립률 상이', '야놀자 회원 | 기간: 상시(프로모션별 변동)', NULL, 'https://nol.yanolja.com/policy/point', '2026-05-13T00:00:00+09:00'),
  ((SELECT id FROM public.brands WHERE name = '야놀자'), '야놀자(NOL 코인)', '포인트 적립', '숙소·레저/티켓 이용 후 후기 작성 시 총 판매금액의 0.5%에 해당하는 금액만큼 야놀자 코인(1원=1C) 적립. 각 숙소·레저/티켓 상품별 최초 작성된 후기는 1,000P YES포인트 추가 적립.', '이용 완료 후 후기 작성 시', '야놀자 회원 | 기간: 상시', NULL, 'https://www.yanolja.com/notice/18799', '2026-05-13T00:00:00+09:00'),
  ((SELECT id FROM public.brands WHERE name = '야놀자'), '현대카드 NOL 카드', '포인트 적립', '야놀자·인터파크(투어/티켓)·트리플 결제 시 결제 금액의 10%를 NOL 포인트로 적립. 일상 영역(커피전문점·편의점·디지털 콘텐츠 서비스) 3개 업종에서도 10% 적립.', '전월 이용 금액 40만원 이상 시 월 1만 / 80만원 이상 시 월 1.2만 NOL 포인트 한도', '현대카드 NOL 카드 회원 | 기간: 상시', NULL, 'https://www.yanolja.com/promotion/nol-promotion', '2026-05-13T00:00:00+09:00'),
  ((SELECT id FROM public.brands WHERE name = '여기어때'), '여기어때(엘리트 멤버십)', '회원 혜택', '베이직(가입 시 기본) 등급에서 회원 전용 프로모션 진행 및 리뷰 작성 시 최대 2,000P 지급(국내 숙소·해외 숙소·공간대여 대상).', '회원 가입 즉시', '여기어때 회원(이용 횟수 3회 미만) | 기간: 상시', NULL, 'https://www.yeogi.com/benefit/elite', '2026-05-13T00:00:00+09:00'),
  ((SELECT id FROM public.brands WHERE name = '여기어때'), '여기어때(엘리트)', '회원 할인 + 쿠폰', '엘리트 등급: 엘리트 전용 쿠폰 제공, 국내 숙소 예약 시 추가 할인(일부 숙소 한정), 레저·티켓 특별가 제공(일부 숙소 한정), 회원 전용 프로모션 진행, 리뷰 작성 시 최대 2,000P 지급.', '조건 충족 시 엘리트 등급 자동 부여', '최근 2년 내 3번 이상 이용완료(실결제 5만원 이상 예약 / 패키지 제외) | 기간: 상시', NULL, 'https://www.yeogi.com/benefit/elite', '2026-05-13T00:00:00+09:00'),
  ((SELECT id FROM public.brands WHERE name = '여기어때'), '여기어때(엘리트 플러스)', '회원 할인 + 쿠폰 + 우선 상담', '엘리트 플러스 등급: 엘리트 플러스 전용 쿠폰 제공, 국내 숙소 예약 추가 할인(일부 숙소 한정), 레저·티켓 특별가(일부 숙소 한정), 우선 상담 서비스 제공, 회원 전용 프로모션, 리뷰 작성 시 최대 2,000P 지급.', '조건 충족 시 엘리트 플러스 등급 자동 부여', '최근 2년 내 7번 이상 이용완료(실결제 5만원 이상 예약 / 패키지 제외) | 기간: 상시', NULL, 'https://www.yeogi.com/benefit/elite', '2026-05-13T00:00:00+09:00'),
  ((SELECT id FROM public.brands WHERE name = '여기어때'), '여기어때', '포인트 적립', '국내 숙소·해외 숙소·공간대여 이용 후 리뷰 작성 시 최대 2,000P 지급. 전 등급(베이직/엘리트/엘리트 플러스) 공통.', '리뷰 1건당 최대 2,000P', '여기어때 회원 | 기간: 상시', NULL, 'https://www.yeogi.com/benefit/elite', '2026-05-13T00:00:00+09:00'),
  ((SELECT id FROM public.brands WHERE name = '인터파크 티켓'), 'KT 멤버십', '할인', '매월 인기 뮤지컬·연극·전시 등을 10~60% 수준으로 할인 예매. KT멤버십 앱에서 예매 가능. 인터파크 결제 시스템 사용하나 예매 수수료 없음.', '매월 제공 공연별 상이', 'KT 멤버십 전등급 | 기간: 상시(매월 공연 변경)', NULL, 'https://membership.kt.com/culture/show/BookingInfo.do', '2026-05-13T00:00:00+09:00'),
  ((SELECT id FROM public.brands WHERE name = '인터파크 티켓'), '인터파크 티켓(TOPING 멤버십)', '유료 멤버십', '공연할인, 선예매, 예매대기, 티켓포장, 웰컴 쿠폰, TOPING Day(매월 쿠폰), TOPING 전용 고객센터, 블루스퀘어 Live-Care Service, Welcome Kit, VIP Room 서비스 등 혜택 제공. 1년 회원제(연회비).', '등급별 연회비 및 가입 즉시 I-Point 지급(Original 1만P / Prime 25만P 등)', 'TOPING 멤버십 가입자(Original/Prime/2만원/1만원 등급) | 기간: 1년(연회원제)', NULL, 'http://ticket.interpark.com/Contents/Toping/TopingClub', '2026-05-13T00:00:00+09:00'),
  ((SELECT id FROM public.brands WHERE name = '인터파크 티켓'), '현대카드 NOL 카드', '포인트 적립', '인터파크(투어/티켓)·야놀자·트리플 결제 시 결제 금액의 10%를 NOL 포인트로 적립.', '전월 이용 금액 40만원 이상 시 월 1만 / 80만원 이상 시 월 1.2만 NOL 포인트 한도(야놀자·인터파크·트리플 합산)', '현대카드 NOL 카드 회원 | 기간: 상시', NULL, 'https://www.yanolja.com/promotion/nol-promotion', '2026-05-13T00:00:00+09:00'),
  ((SELECT id FROM public.brands WHERE name = '에버랜드'), 'SKT T멤버십', '할인', '종일권 본인 40% 할인 + 동반 3인 30% 할인. T 멤버십 전용 스마트 예약 페이지에서 종일권 구매 후 카카오톡 알림톡/문자로 QR 코드 수령, 에버랜드 정문에서 QR 코드 제시.', 'T 멤버십 카드당 일 1회 다운로드', 'T 멤버십 회원(전등급) + 본인 + 동반 3인 | 기간: 상시', NULL, 'https://sktmembership.tworld.co.kr/mps/pc-bff/benefitbrand/detail.do?brandId=5244', '2026-05-13T00:00:00+09:00'),
  ((SELECT id FROM public.brands WHERE name = '에버랜드'), 'KT 멤버십', '할인', '에버랜드 종일권 본인 40% + 동반 3인 20% 할인. 현장 매표 시 KT멤버십 바코드 제시.', '1일 1회, 본인에 한함', 'KT 멤버십 전등급 | 기간: 상시', NULL, 'https://membership.kt.com/discount/partner/C23/106/PartnerDetail.do', '2026-05-13T00:00:00+09:00'),
  ((SELECT id FROM public.brands WHERE name = '에버랜드'), 'KT 멤버십(생일혜택)', '할인', '에버랜드 이용권 50% 할인. KT 멤버십 앱 생일배너에서 상세 내용 확인.', '1인 1회, 생일 당월 한정', 'KT 멤버십 전등급 | 기간: 상시(생일 당월)', NULL, 'https://membership.kt.com/discount/partner/C23/106/PartnerDetail.do', '2026-05-13T00:00:00+09:00');
