-- 사용자 검토용 샘플 (처음 10행). 검토 후 0003_seed_discounts.sql 실행.

INSERT INTO public.discounts (brand_id, provider, type, rate, limit_amount, conditions, is_stackable, source_url, updated_at) VALUES
  ((SELECT id FROM public.brands WHERE name = '아웃백 스테이크하우스'), '브랜드 (부메랑클럽)', '멤버십 결제 할인', '부메랑 카드 결제 시 10% 할인 또는 2% 포인트 적립', '상시 (제휴할인과 중복 불가)', '부메랑클럽 회원, 부메랑 카드 소지자 | 기간: 상시', NULL, 'https://m.outback.co.kr/benefit/membershipBenefit.do?menuIdx=304', '2026-05-12T00:00:00+09:00'),
  ((SELECT id FROM public.brands WHERE name = '아웃백 스테이크하우스'), '브랜드 (부메랑클럽)', '기념일 쿠폰', '프리미엄 스테이크 한정 1만원 할인 쿠폰', '연 1회 (기념일 전후)', '부메랑클럽 회원, 기념일 등록 시 | 기간: 기념일 전후', NULL, 'https://m.outback.co.kr/benefit/membershipBenefit.do?menuIdx=304', '2026-05-12T00:00:00+09:00'),
  ((SELECT id FROM public.brands WHERE name = '아웃백 스테이크하우스'), '브랜드 (부메랑클럽)', '등급 시즌 쿠폰', 'GOLD 시즌 메뉴 쿠폰 2매 / PLATINUM 3매 (3-5월 치킨텐더 샐러드, 6-8월 스파이시 씨푸드 알리오 올리오 등)', '시즌별 매수 한정', 'GOLD / PLATINUM 등급 회원 | 기간: 분기별 변경', NULL, 'https://m.outback.co.kr/benefit/membershipBenefit.do?menuIdx=304', '2026-05-12T00:00:00+09:00'),
  ((SELECT id FROM public.brands WHERE name = '아웃백 스테이크하우스'), '브랜드 (부메랑클럽)', '신규/회원 쿠폰', '신규 가입 시 오지치즈후라이즈 교환 쿠폰 2매 + 에이드/음료 교환 쿠폰 + 와인 콜키지 free', '가입 즉시 / 회원 상시', '부메랑클럽 신규 회원 | 기간: 회원 가입 시 / 상시', NULL, 'https://www.outback.co.kr/', '2026-05-12T00:00:00+09:00'),
  ((SELECT id FROM public.brands WHERE name = '아웃백 스테이크하우스'), 'SKT (T멤버십)', '통신사 할인', 'VIP/GOLD 15% 할인 또는 적립, SILVER 5% 할인 또는 적립. T+포인트 사용 가능', '1일 1회, 최대 이용금액 20만원 한도', 'SKT T멤버십 회원, T멤버십 앱 OTB/플라스틱 카드 제시 | 기간: 상시', NULL, 'https://m.outback.co.kr/main.do?menuIdx=117', '2026-05-12T00:00:00+09:00'),
  ((SELECT id FROM public.brands WHERE name = '아웃백 스테이크하우스'), 'KT (KT멤버십)', '통신사 할인', 'VVIP/VIP/GOLD 15% 할인, 일반/WHITE/SILVER 5% 할인. VVIP 초이스: 6만원 이상 결제 시 3만원 할인(월 1회)', '1일 1회 · 결제 20만원 한도 / VVIP 초이스 월 1회', 'KT 멤버십 회원, 멤버십 카드 제시 | 기간: 상시', NULL, 'https://membership.kt.com/discount/partner/PartnerList.do', '2026-05-12T00:00:00+09:00'),
  ((SELECT id FROM public.brands WHERE name = '아웃백 스테이크하우스'), 'OK캐쉬백', '포인트 제휴', '25% 할인(15% 포인트 차감 + 10% 추가할인) 또는 10% 적립 중 택1', '1일 1회 / 비밀번호 4자리 필요', 'OK캐쉬백 회원 (OK캐쉬백 로고 카드 / 모바일) | 기간: 상시', NULL, 'https://m.outback.co.kr/main.do?menuIdx=117', '2026-05-12T00:00:00+09:00'),
  ((SELECT id FROM public.brands WHERE name = '아웃백 스테이크하우스'), 'LG U+ (유플투쁠)', '통신사 할인', '슈퍼투쁠데이 외식 혜택 (월 단위 다른 형태로 제공, 최근 사례: 선착순 할인 쿠폰)', '월별 선착순', 'LG U+ 멤버십 회원 (U+one 앱) | 기간: 월간 (둘째 화 ~ 넷째 목)', NULL, 'https://www.lguplus.com/benefit-plus', '2026-05-12T00:00:00+09:00'),
  ((SELECT id FROM public.brands WHERE name = '빕스 (VIPS)'), '브랜드 (CJ ONE)', '매니아 등급 쿠폰', '연 2회·10만원 이상 이용 시 추가 10% 할인 쿠폰 4매 제공. VVIP는 스테이크 무료 + 상시 15% 할인', '쿠폰 4매, 매주 수요일 매니아데이 15% 할인', 'VIPS 매니아 등급 진입 고객 (CJ ONE 연동) | 기간: 등급 부여 후 1년', NULL, 'https://www.ivips.co.kr/promotion', '2026-05-12T00:00:00+09:00'),
  ((SELECT id FROM public.brands WHERE name = '빕스 (VIPS)'), '브랜드 (CJ ONE)', '포인트 적립', '결제금액의 0.5% CJ ONE 포인트 적립 (제휴할인 후 결제금액 기준 적립 가능)', '1일 5회까지 적립', 'CJ ONE 회원 | 기간: 상시', NULL, 'https://www.cjone.com/cjmweb/point-card/brand/detail.do?coopco_cd=7020&brnd_cd=2040', '2026-05-12T00:00:00+09:00');
